name: CI Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual triggering for debugging
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.8'  # Match your project's .NET Framework version
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore Dependencies
        run: msbuild -t:restore
      - name: Build Project
        run: msbuild CybersecurityChatbot.sln -t:build -p:Configuration=Release
      - name: Verify Build Output
        shell: powershell  # Explicitly use PowerShell
        run: |
          if (Test-Path "bin\Release") {
            Write-Output "Build output found:"
            dir bin\Release
          } else {
            Write-Output "Build output directory bin\Release not found."
            exit 1
          }
